name: CropCollect

on:
  workflow_dispatch:
  schedule:
    - cron: '30 14 * * *'  # Adjust the cron schedule as needed

jobs:
  run-bot:
    runs-on: ubuntu-latest

    env:
      AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache
      EMAIL: ${{ secrets.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2 

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"  # Adjust to your preferred Python version
        cache: "pip"

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 120

    - name: Run sb-poll-search.py
      run: |
        python sb-poll-search.py

    - name: Run sb-poll-search-2.py
      run: |
        python sb-poll-search-2.py
